# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Receiver' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Receiver
  pod 'Alamofire', '~> 4.5'

  target 'ReceiverUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
